config/routes.rb
BandSchedulerBdd::Application.routes.draw do

  get "people/index"
  get "people/new"

  get "roles/index"
  get "roles/new"

  resources :people
  resources :roles
  resources :performances

  resources :events

  match 'scheduler/generate' => 'scheduler#default_generate', :as => 'generate_schedule'
  match 'scheduler/clear' => 'scheduler#clear', :as => 'clear_schedule'
  
  match 'events/:event_id/remove_person/:person_id' => 'events#remove_person', :as => 'event_remove_person'

  root :to => "menu#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_and_belongs_to_many :roles, :delete_sql =>
    'DELETE FROM people_roles where person_id = #{id}'

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def events_in_a_row(event)
    size = 100
    result = 0
    while(size != 0)
      event = event.previous_event
      unless event.nil?
        eprs = EventPersonRole.where(:event_id => event.id, :person_id => self.id)
        result = result + eprs.size
        size = eprs.size
      else
        size = 0
      end
    end
    result
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
    @roles = Role.all
  end

  def create
    if request.post?
      person = Person.new(params[:person].merge(:roles => Role.find(params[:roles])))
      person.save
    end
    redirect_to people_path
  end

  def show
    @person = Person.find(params[:id])
  end

  def destroy
    Person.delete(params[:id])
    redirect_to people_path
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/index.html.haml
= link_to  "Add Person",  people_new_path
%br
= @people.size 
= @people.size == 1 ? "Person" : "People" 
found!
%br

%table
  %th
    Name
  %th
    Roles
  %th
    Delete
  - @people.each do |person|
    %tr
      %td
        = link_to "#{person.first_name} #{person.last_name}", person
      %td
        - person.roles.each do |role|
          = role.name
      %td{:style => "text-align: center"}
        = link_to image_tag("delete.png", :border => 0), person, 
          :method => :delete, :confirm => "Are you sure?"

app/views/people/new.html.haml
= form_for @person do |f|

  =f.label :first_name
  =f.text_field :first_name
  %br

  =f.label :last_name
  =f.text_field :last_name
  %br

  - @roles.each do |role|
    %label
      = role.name
      = check_box_tag "roles[]", role.id
      %br
  
  = f.submit "Save"

app/views/people/show.html.haml
#name
  #{@person.first_name} #{@person.last_name}

#roles
  Add area to change roles
#days_off
  Add area to ask for days off