config/routes.rb
BandSchedulerBdd::Application.routes.draw do

  get "people/index"
  get "people/new"

  get "roles/index"
  get "roles/new"

  resources :people
  resources :roles
  resources :performances

  resources :events

  match 'scheduler/generate' => 'scheduler#default_generate', :as => 'generate_schedule'
  match 'scheduler/clear' => 'scheduler#clear', :as => 'clear_schedule'
  
  match 'events/:event_id/remove_person/:person_id' => 'events#remove_person', :as => 'event_remove_person'

  root :to => "menu#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  def index
    @date = params[:month] ? params[:month].to_date : Date.today
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/index.html.haml
#admin
  #admin-header
    Admin
  = link_to "Roles", roles_path
  %br
  = link_to "People", people_path
  %br
  = link_to "Performances", performances_path
  %br
  = link_to "Generate Schedule", generate_schedule_path 
  %br
  = link_to "Clear Schedule", clear_schedule_path

#calendar
  Found #{Event.all.size} Events
  #calendar-header
    = link_to "<", :month => (@date.beginning_of_month-1).strftime("%m/01/%Y")
    = @date.strftime("%B %Y")
    = link_to ">", :month => (@date.end_of_month+1).strftime("%m/01/%Y")
  %br
  - calendar_for Event.all, :year => @date.year, :month => @date.month do |calendar|
    = calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
    - calendar.day(:day_method => :start_time) do |date, events|
      = date.day
      %ul
        - for event in events
          %li
            = link_to event.name, event_path(event.id)
            = event.status