config/routes.rb
BandSchedulerBdd::Application.routes.draw do

  get "people/index"
  get "people/new"

  get "roles/index"
  get "roles/new"

  resources :people
  resources :roles
  resources :performances

  resources :events

  match 'scheduler/generate' => 'scheduler#default_generate', :as => 'generate_schedule'
  match 'scheduler/clear' => 'scheduler#clear', :as => 'clear_schedule'
  
  match 'events/:event_id/remove_person/:person_id' => 'events#remove_person', :as => 'event_remove_person'

  root :to => "menu#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :people

  has_many :performance_roles, :dependent => :delete_all
  has_many :performances, :through => :performance_roles

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  
  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def create
    Role.create!(params[:role])
    redirect_to roles_index_path
  end

  def destroy
    Role.delete(params[:id])
    redirect_to roles_path 
  end
 
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/index.html.haml
= link_to "Add Role", roles_new_path
%br

= @roles.size 
= @roles.size == 1 ? "Role" : "Roles" 
found!
%br

%table
  %th
    Name
  %th
    Delete
  - @roles.each do |role|
    %tr
      %td{:style => "width: 200px"}
        = role.name
      %td{:style => "text-align: center"}
        = link_to image_tag("delete.png", :border => 0), role, 
          :method => :delete, :confirm => "Are you sure?"

app/views/roles/new.html.haml
=form_for @role do |f|

  =f.label :name
  =f.text_field :name
  %br

  =submit_tag "Save"