config/routes.rb
BandSchedulerBdd::Application.routes.draw do

  get "people/index"
  get "people/new"

  get "roles/index"
  get "roles/new"

  resources :people
  resources :roles
  resources :performances

  resources :events

  match 'scheduler/generate' => 'scheduler#default_generate', :as => 'generate_schedule'
  match 'scheduler/clear' => 'scheduler#clear', :as => 'clear_schedule'
  
  match 'events/:event_id/remove_person/:person_id' => 'events#remove_person', :as => 'event_remove_person'

  root :to => "menu#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  has_many :performance_roles, :dependent => :delete_all
  has_many :roles, :through => :performance_roles

 #validates_presence_of :name

  validates_numericality_of :start_minute, :on => :create, :allow_nil => true,
                            :greater_than_or_equal_to => 0, :less_than => 60

  validates_numericality_of :start_hour, :on => :create, :allow_nil => true,
                            :greater_than_or_equal_to => 0, :less_than => 24

  class WeeklyValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      if record.weekly and record.one_off
        record.errors[attribute] << "can't be specified if one off is"
      end
    end
  end

  validates :weekly, :weekly => true

  def last_event
    Event.order("start_time").where(:performance_id => self.id).last
  end

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController

  def index
    @performances = Performance.all
  end

  def new
    @performance = Performance.new
    @roles = Role.all
  end

  def create
    redirect_to performances_path
    if request.post?
      performance = Performance.new(params[:performance])
      params[:roles].each do |role|
        if role[1].to_i > 0
          performance.performance_roles << PerformanceRole.new(:role_id => Role.find(role[0]).id,
                                                               :quantity => role[1], 
                                                               :optional => params[:optionals].include?(role[0]))
        end
      end
      performance.save
    end
  end

end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/index.html.haml
= link_to  "Add Performance",  new_performance_path
%br

= @performances.size
= @performances.size == 1 ? "Performance" : "Performances"
Found!
%br

- @performances.each do |performance|
  - performance.performance_roles.each do |pr|
    = pr.quantity 
    = pr.quantity == 1 ? pr.role.name : pr.role.name.pluralize
  %br

app/views/performances/new.html.haml
= form_for @performance do |f|

  = f.label :name
  = f.text_field :name
  %br
  = f.label :start_time
  = f.select :start_hour, options_from_collection_for_select(0..23, "to_s", "to_s")
  = f.select :start_minute, options_from_collection_for_select(0..59, "to_s", "to_s")
  %br

  #choice
    %ul 
      %li
        %a{:id => "one_off_a", :class => "selected", :href => "#one_off"}
          One Off
      %li
        %a{:id => "weekly_a", :href=>"#weekly"}
          Weekly
  #one_off
    = f.label :one_off
    = f.text_field :one_off
  #weekly
    = f.label :weekly
    = f.text_field :weekly

  :javascript 

  - @roles.each do |role|
    %label
      = text_field_tag "roles[#{role.id}]"
      \# of #{role.name.pluralize}
      = check_box_tag "optionals[]", role.id
      Required
      %br

  = f.submit "Save"